### ISSUE TITLE
What kind of constraints do we have for subset IDs?

### ISSUE THREAD

**Issue by drageset** [statisticsnorway/klass-subsets-api#14]
What kind of (special) characters do we (not) allow for use in subset IDs? 

I think it's nice to allow A-Z, a-z, 0-9, -, _

**Comment by alina-lapina** [comment]
- The many different symbols are allowed, the higher number of possible unique combinations users can create, especially with the right variable length. 
- We have to follow al least same restrictions LDS has for IDs. 
- We definitely cannot allow `/` `\` `&` `=` `?` and such, because it could be interpreted in URLs queries. 
- No other alphabets to avoid encoding issues.
- No whitespace and % to close a possibility to use other encodings and null byte involved attacks.
- We cannot allow < > to avoid injections
- etc

**I agree with your suggestion.** We can whitelist more symbols later if needed.
