### ISSUE TITLE
Update a PUBLISHED subset

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-api#37]
### Bug
It should be possible to update name, validUntil, shortDescription, description, createdBy, administrativeDetails.administrativeType('ANNOTATION').values.
The change has to affect all published versions of the subset.

### Solution A:
- write a patch to the last version and pick this data up for the earlier versions.
- write a patch to each existent version to avoid merge;

### Example:
Storage: 
[
{ name: A, version: 1.0.0, DRAFT },
{ name: A, version: 1.0.1, OPEN},
{ name: A, version: 2.0.0, OPEN},
{ name: B, version: 2.0.1, OPEN }, _/updated name/_
{ name: C, version: 3.0.0, DRAFT },
]
GET /versions 
[
{ name: B, version: 1.0.1, OPEN },
{ name: B, version: 2.0.0, OPEN },
{ name: C, version: 3.0.0, DRAFT },
]

**Comment by drageset** [comment]
**Solution:** 

In GET /versions
After the final list of most recent major versions is built
Find the newest version that is OPEN, and apply the name stored in this version to each previous version.

**Comment by drageset** [comment]
@alina-lapina validUntil is different for each major version of a subset, and so should not be overwritten. The createdBy might also be different for each major version: The fact that organization A made major version 1 is not changed by the fact that organization B makes major version 2? The description and short description should maybe also be different from version to version, because the version contains different things and so a different description is appropriate. The description might also contain info on why a new version was made, and so it should not be applied to the old versions as well. The only value that I believe should truly overwrite all versions is "name", because we agreed on that with Anne Gro. Do you agree?

**Comment by alina-lapina** [comment]
`validUntil` is not version dependent, It is one for the whole subset. It has to be flexible. It can also be null.
Version's validity period is based on `verisionValidFrom` and next version's `versionValidFrom` or, if last version, subset's validUntil.

Read a discussion here https://github.com/statisticsnorway/gsim-raml-schema/pull/29

**Comment by alina-lapina** [comment]
### createdBy
> The createdBy might also be different for each major version: 
> The fact that organization A made major version 1 is not changed 
> by the fact that organization B makes major version 2?

It's interesting. We need Anne Gro's opinion here.
